---
title: "第3回課題" 
title-prefix: "プログラミング基礎" 
pagetitle: "プログラミング基礎"  
date: "`r Sys.Date()`"
output: 
  # ショートカットは ctrl + com + c でコメント
  html_document:
    # 全体的な見た目 
    theme:
      version: 4
      bootswatch: simplex # 好みに合わせて変更化
    number_sections: TRUE # 番号付与
    # 不便に感じないため
    toc: TRUE # 目次表示
    toc_depth: 3 # 見出しレベル3まで表示
    toc_float: TRUE # 目次の自動追尾
    self_contained: TRUE # htmlファイル単独でも表示可能に # hide
    # コードの見た目
    highlight: tango # 好みに合わせて変更化
    # その他
    md_extensions: "+ignore_line_breaks" 
---


# 発展課題5.6
丸括弧内は、別の表現である。

下記のプログラムは、変数を利用して、姓名を入れ替えるプログラムである。

- ポイント1
  - 2行目では、太郎という名前の文字列をAというラベル（名前）で管理
    - (または、変数Aに自分の名前である太郎を代入)
  - 3行目では、関学という苗字の文字列をBというラベル（名前）で管理
    - (または、変数Bに自分の苗字である関学を代入)
- ポイント2
  - 変数Wを用いて太郎に複数のラベルを割り当てる。変数Aには太郎が代入されているため、W = Aの時点で、太郎にAというラベルと、Wというラベルが割り当てられることになる
  - 意図としては、次の命令で太郎という名前から、関学という苗字に、Aというラベルの割り当てを変更するため、太郎にアクセスできるWを用意する。
- ポイント3
  - 変数Aに、関学という苗字を割り当てる
- ポイント4
  - 変数Bに、変数Wの太郎を割り当てる

```
# ポイント1
A = '太郎'
B = '関学'
print('入れ替え前',A, B)
W = A # ポイント2
A = B # ポイント3
B = W # ポイント4
print('入れ替え後',A, B)
```

## 不足気味な解答例
- AやBについて、変数またはラベル、文字列などの記述がない。
- 名前や苗字を代入などの具体的なオブジェクを表現できていない
  - 例：Bに苗字を代入

# 発展課題5.8

```
k = 60 # 時速の設定
masatu = 0.7 # 摩擦係数の設定
kyori = k ** 2 / (254 * masatu) # 停止距離の計算
print('摩擦係数', masatu, 'としたとき、')
print('時速', k, 'kmの車はブレーキを踏んでから', kyori, 'm走ります。')
```

変数を利用する利点は次のようなものが考えられる。

- 様々な時速の停止距離を求める際に、時速の変数kの値を変えれば、時速ごとの停止距離を求めることができる
- 変数masatuは、道路の状況により変化するため、その状況に合わせた摩擦係数を設定して計算できる。



# 発展課題5.10

## TurtleGraphicsError
-	エラーの種類：TurtleGraphicsError
- 解説は教科書同様

## SyntaxError: can’t assign to operator
- エラーの種類：SyntaxError
- エラーの発生例：50 = 変数名のように、逆に書いてしまう場合

### invalid syntax 
「変数名 =　」　のように途中が抜けてしまう場合 

## NameError: name 〇〇 is not defined
- エラーの種類：NameError
- エラーの発生例：代入していない変数を利用しようとしている。

## 回答不足
- 例：〇〇行目のXXXXの後に〇〇〇〇の入れ忘れ 

# 前回の課題の解答例
## 構文エラー（全角空白）
- エラーの種類：Syntax Error（構文エラー）
- 発生箇所：「from turtle　import *」の行
  - これは、エラーメッセージに「Cell In[2] line 1 」や「---->」の記載があるため、それらのメッセージから1行目の「from turtle　import *」に不備があることがわかる（以後の解答では重複するため記載しない）。
- 発生理由：「invalid non-printable character U+3000」とエラーメッセージが出力されているため、turtle　import * のどこかに全角の空白があることがわかる。具体的に、turtle と importの間に全角空白がある。
- 解消方法：全角空白を半角空白に置き換える

### その他種類
- 発生箇所：「from turtle import　*」
- 発生箇所：「from turtle import *　」
- 発生箇所：right(　144)
  - この事例は今年初めて


## 構文エラー（存在しない基礎的な命令）
- エラーの種類：Syntax Error（構文エラー）
- 発生箇所：「From turtle import *」の行
- 発生理由：「invalid syntax」とエラーメッセージが出力されているため、どこかにPythonの文法に違反するソースコードが存在する。具体的に、fromではなくFromとなっており、スペルミスによる構文エラーが発生している。タートルグラフィックスなどのライブラリを読み込むとき、すなわち、便利な機能を利用するときには、「from 機能名<モジュール名やライブラリ名> import *」という命令が決まり文句になっているため、構文エラーが発生する。
- 解消方法：From を fromに修正

### その他種類
- 発生箇所：「from turtle import」
- 発生箇所：「from turtle import +」

## 構文エラー（全角括弧）
- エラーの種類：Syntax Error（構文エラー）
- 発生箇所：「forward（100）」の行
- 発生理由：「invalid character '（'」とエラーメッセージが出力されているため、全角括弧「（」が存在することがわかる。この全角括弧が存在することにより、forward命令は、どれくらい進むのかが記載を見つけられなくなるため、構文エラーが発生する。
- 解消方法：全角を半角に置き換える


# ModuleNotFoundError
## モジュール読み込みエラー（タイプミス）
- エラーの種類：ModuleNotFoundError
- 発生箇所：「from turtl import *」
- 発生理由：「No module named 'turtl'」とエラーメッセージが出力されているため、turtl　というモジュール（Pythonのプログラムの集まり）が存在しないことがわかる。単にturtleのタイプミスが原因である。
- 解消方法：turtl を turtleに書き換える

# NameError
## 未定義の命令利用（関数の場合）
- エラーの種類：NameError
- 発生箇所：「forward(100)」
- 発生理由：「“name 'forward' is not defined” 」というエラーメッセージが出力されているため、タートルグラフィックスのforwardという命令は、現在利用できないことを意味している。これは「from turtle import *」というタートルグラフィックスに必要な命令の読み込み処理がされていないためである。
- 解消方法：タートルグラフィックスを利用する命令「from turtle import *」を冒頭で実行する

### その他事例
- 発生箇所：「light(144)」
  - rightの間違いである
  - lightという命令が存在しない or 現在利用できないため
    - 同類なケース：「forword」
    - 同類なケース：「forward100」
- 発生箇所：「don」
  - done()の間違え

# TypeError
## 括弧の中の数値未記入
- エラーの種類：TypeError
- 発生箇所：「rigth()」
- 発生理由：「right() missing 1 required positional argument :'angle'」と記載されている。これはrightという命令には、何度回転するかの数値が必要であるため、それが記載されていないことに起因する。TypeError ではあるが、命令ごとに必要最低限の引数が設定されていないことが問題である。つまり、記入が不十分であった。
- 解消方法：right(100)の様に記述する。

# IndentationError
## 冒頭の空白
- エラーの種類：IndentationError
- 発生箇所：「 rigth(144)」
- 発生理由：「unexpected indent」とエラーメッセージが出力されているため、予期されない場所に不要なインデント（空白）が存在しないことを意味している。これは、「 rigth(144)」のように命令の冒頭に空白が存在することで発生している。Pythonでは空白は特別な意味を持つ。詳しくはif文やfor文の章で解説されるが、処理を区切るために空白を用いることがある。その区切りをする前には、いくつかの命令を記載する必要がある。その命令がないままに命令の前に空白が置かれたため発生した。
- 解消方法：行の冒頭の空白を削除する

# 不完全解答例
下記のような事例では部分点

## 説明不足
- エラーの種類を明示的に答えてない。スクリーンショットでは、わかっていたとしても、エラーの種類を的確に答えているわけではない。
- 説明不足
  - 例：done()をdon()としたため
    - たしかに、単にスペルミスなのだが... それが何の種類のエラーで、どんなエラーメッセージが出力され、それがどんな意味を持っているかを説明していない。スペルミスによってdon()という命令を実行しようとしていることに気がついているかは、レポートからは判断不可能
- 単に、エラーメッセージだけ書いてある

## 複数のエラー
二つ以上のエラーを発生させており、部分的にしか説明していない。

## Terminator 
forward (100)やleft('144')でエラーを発生させたつもりが、インタプリタ由来のエラーが優先されてしまうため、エラーの種類の記述ミスがある。Terminatorは教科書参照。

## 部分的なエラーメッセージだけでエラーがわかる
NameErrorという文字だけでは、詳細は不明である。NameError: name 〇〇 is not defined と エラーの箇所を示すメッセージから判定できる。単に「NameError」から〇〇が間違い、という説明は説明不足

## プログラムや実行結果不掲載
プログラムや実行結果もない場合は、課題の要件を満たしていない

# 不正解事例
## エラーメッセージと解説が全く一致していない

